server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carwashdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration

jwt:
  secret: MyJwtSecretKey123456
  expiration: 3600000  # 1 ??? ? ?????????????